baseurl = "http://peach-studio.github.io"
title = "桃子工作室"
theme = "dimension"
languageCode = "zh_cn"
defaultContentLanguage = "zh_cn"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = "专注于新一代的网站设计与研发"
  logoimage = "/images/peach.png"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.zh_cn]
languageName = "简体中文"
weight = 1

[languages.en]
languageName = "English"
weight = 2
title = "Peach Studio"
description = "Focus on a new generation of website design and development"
